name: Bug report
description: Report a problem
title: '[Bug]: '
labels: ['bug']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide minimal reproduction steps
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Node version, package version, OS

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell
    validations:
      required: false
