name: Feature request
description: Suggest an improvement or new capability
title: '[Feature]: '
labels: ['enhancement']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome. Please keep them focused and actionable.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the behavior you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches?
    validations:
      required: false
