/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

import { AuthContextType, AuthPorts, AuthProvider, useAuth } from '@/AuthProvider';
import { AuthRoutes } from '@/AuthRoutes';
import {
  createSeamlessAuthClient,
  CredentialUpdateResult,
  CreateOrganizationInput,
  CurrentUserResult,
  FinishOAuthLoginInput,
  FinishOAuthLoginResult,
  LoginInput,
  LoginMethod,
  LoginStartResult,
  MessageResult,
  OAuthProvider,
  OAuthProvidersResult,
  PublicSystemConfigResult,
  OrganizationMemberInput,
  OrganizationMemberUpdateInput,
  OrganizationMembersResult,
  OrganizationMembershipResult,
  OrganizationResult,
  OrganizationSwitchResult,
  OrganizationsResult,
  PasskeyLoginData,
  PasskeyAttachment,
  PasskeyMetadata,
  PasskeyRegistrationData,
  RegisterInput,
  RegisterPasskeyOptions,
  SeamlessAuthClient,
  SeamlessAuthClientOptions,
  StartOAuthLoginInput,
  StartOAuthLoginResult,
  StepUpMethod,
  StepUpStatus,
  StepUpPrfData,
  TotpEnrollmentStartResult,
  TotpStatus,
  UpdateOrganizationInput,
} from '@seamless-auth/client';
import {
  getOAuthErrorCode,
  getPasskeyPolicyErrorCode,
  getWebAuthnErrorDetail,
  isUnauthenticated,
  OAuthErrorCode,
  PasskeyPolicyErrorCode,
  SeamlessAuthError,
  WebAuthnErrorDetail,
} from '@seamless-auth/client';
import type { SeamlessAuthResult } from '@seamless-auth/client';
import {
  encodePrfSalt,
  extractPasskeyPrfResult,
  isPasskeyPrfSupported,
  PasskeyPrfInput,
  PasskeyPrfResult,
} from '@seamless-auth/client';
import { useAuthClient } from '@/hooks/useAuthClient';
import { useAuthorizedFetch } from '@/hooks/useAuthorizedFetch';
import { hasNonPasskeyLoginMethod, useLoginMethods } from '@/hooks/useLoginMethods';
import { usePasskeySupport } from '@/hooks/usePasskeySupport';
import { hasScopedRole, roleGrantsAccess } from '@seamless-auth/client';
import {
  Credential,
  Organization,
  OrganizationMembership,
  User,
} from '@seamless-auth/client';
import type {
  OAuthRedirectOutcome,
  OAuthRedirectPort,
  PasskeyPort,
  StoredTokens,
  TokenStoragePort,
  TransportOptions,
} from '@seamless-auth/client';

export {
  AuthProvider,
  AuthRoutes,
  createSeamlessAuthClient,
  encodePrfSalt,
  extractPasskeyPrfResult,
  getOAuthErrorCode,
  getPasskeyPolicyErrorCode,
  getWebAuthnErrorDetail,
  hasNonPasskeyLoginMethod,
  hasScopedRole,
  isPasskeyPrfSupported,
  isUnauthenticated,
  roleGrantsAccess,
  SeamlessAuthError,
  useAuth,
  useAuthClient,
  useAuthorizedFetch,
  useLoginMethods,
  usePasskeySupport,
};
export type {
  CredentialUpdateResult,
  AuthContextType,
  AuthPorts,
  Credential,
  CreateOrganizationInput,
  CurrentUserResult,
  FinishOAuthLoginInput,
  FinishOAuthLoginResult,
  LoginInput,
  LoginMethod,
  LoginStartResult,
  MessageResult,
  OAuthErrorCode,
  OAuthProvider,
  OAuthProvidersResult,
  OAuthRedirectOutcome,
  OAuthRedirectPort,
  Organization,
  OrganizationMemberInput,
  OrganizationMembership,
  OrganizationMemberUpdateInput,
  OrganizationMembersResult,
  OrganizationMembershipResult,
  OrganizationResult,
  OrganizationSwitchResult,
  OrganizationsResult,
  PasskeyLoginData,
  PasskeyAttachment,
  PasskeyMetadata,
  PasskeyPolicyErrorCode,
  PasskeyPort,
  PasskeyPrfInput,
  PasskeyPrfResult,
  PasskeyRegistrationData,
  PublicSystemConfigResult,
  RegisterInput,
  RegisterPasskeyOptions,
  SeamlessAuthClient,
  SeamlessAuthClientOptions,
  SeamlessAuthResult,
  StartOAuthLoginInput,
  StartOAuthLoginResult,
  StepUpMethod,
  StepUpStatus,
  StepUpPrfData,
  StoredTokens,
  TokenStoragePort,
  TotpEnrollmentStartResult,
  TotpStatus,
  TransportOptions,
  UpdateOrganizationInput,
  User,
  WebAuthnErrorDetail,
};
